### ISSUE TITLE
suggestion: A "remember me" option on log in.

### ISSUE THREAD

**Issue by scooterboo** [vrsites/vrsites.com#4]
I have to log in four times a day because I keep getting logged out.

**Comment by sirkitree** [comment]
Great suggestion @scooterboo. This is something that bugged me about the old site as well.

Have you tried the new beta site yet? In case you missed the announcement, you can sign up for our new beta and migrate your rooms over to the new site now. Unfortunately, this means the original site will most likely not get many updates since our time and resources are being spent on improving the new and improved beta site. If you get a chance to check it out, we'd love to hear your feedback.

http://beta.vrsites.com/
